SET FEEDBACK 1
SET NUMWIDTH 10
SET LINESIZE 80
SET TRIMSPOOL ON
SET PAGESIZE 100

-------------------------------------------------------------------------------
REM ********************************************************************
REM Create the CENTROCOSTOS table to hold all teh Centro de Costos information

Prompt ******  Creating CENTROCOSTOS table ....
--DROP TABLE CENTROCOSTOS;

CREATE TABLE CENTROCOSTOS
    ( ID_CENTRO INT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1)
    , NOMBRE VARCHAR2(100) NOT NULL
	, SALDO INT NOT NULL
	, PRESUPUESTO INT NOT NULL
	, GASTO INT NOT NULL
	, MES_GASTO VARCHAR2(10) NOT NULL
    );

CREATE UNIQUE INDEX INDX_CENTROCOSTOS_PK
ON CENTROCOSTOS (ID_CENTRO);

ALTER TABLE CENTROCOSTOS
ADD ( CONSTRAINT INDX_CENTROCOSTOS_PK
       		 PRIMARY KEY (ID_CENTRO)
    ) ;
    
-------------------------------------------------------------------------------

REM ********************************************************************
REM Create the DEPARTAMENTOS table to hold the DEPARTMENTS

Prompt ******  Creating DEPARTAMENTOS table ....
--DROP TABLE DEPARTAMENTO;

CREATE TABLE DEPARTAMENTOS
	( ID_DEPARTAMENTO INT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1)
	, NOMBRE VARCHAR2(100) NOT NULL
	, USUARIOS INT NOT NULL
	, ID_CENTRO_COSTOS INT NOT NULL
	);

CREATE UNIQUE INDEX INDX_DEPARTAMENTO_PK
ON DEPARTAMENTOS (ID_DEPARTAMENTO);

ALTER TABLE DEPARTAMENTOS
ADD ( CONSTRAINT INDX_DEPARTAMENTO_PK
       		 PRIMARY KEY (ID_DEPARTAMENTO)
    , CONSTRAINT CENTRO_DEP_FK
			 FOREIGN KEY (ID_CENTRO_COSTOS)
			 REFERENCES CENTROCOSTOS(ID_CENTRO)
    ) ;
	

-------------------------------------------------------------------------------

REM ********************************************************************
REM Create the USUARIOS table to hold the LIST OF USUARIOS FOR THE CENTRO DE COSTOS

Prompt ******  Creating USUARIOS table ....
--DROP TABLE USUARIOS;

CREATE TABLE USUARIOS
	( ID_USUARIO INT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1)
	, NOMBRE VARCHAR2(100) NOT NULL
	, PRIMERAPELLIDO VARCHAR2(100) NOT NULL
	, SEGUNDOAPELLIDO VARCHAR2(100) NOT NULL
	, USUARIO_RED VARCHAR2(100) NOT NULL
	, CORREO VARCHAR2(100) NOT NULL
	, NUMERO_TARJETA VARCHAR2(16) NOT NULL
	, ID_DEPARTAMENTO INT NOT NULL
	);

CREATE UNIQUE INDEX INDX_USUARIO_PK
ON USUARIOS (ID_USUARIO);

ALTER TABLE USUARIOS
ADD ( CONSTRAINT INDX_USUARIO_PK
       		 PRIMARY KEY (ID_USUARIO)
	, CONSTRAINT ID_DEP_FK
			 FOREIGN KEY (ID_DEPARTAMENTO)
			 REFERENCES DEPARTAMENTOS(ID_DEPARTAMENTO)
    ) ;

-------------------------------------------------------------------------------

REM ********************************************************************
REM Create the RUBROS table to hold the LIST OF rubros FOR EACH centro de costos

Prompt ******  Creating RUBROS table ....
--DROP TABLE FACTURA;

CREATE TABLE RUBROS
	( ID_RUBRO INT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1)
	, NOMBRE_RUBRO VARCHAR2(100) NOT NULL
	, DESCRIPCION VARCHAR2(100) NOT NULL
	, MES VARCHAR2(10) NOT NULL
	, ID_CENTRO_COSTOS INT NOT NULL
	);

CREATE UNIQUE INDEX INDX_RUBROS_PK
ON RUBROS (ID_RUBRO);

ALTER TABLE RUBROS
ADD ( CONSTRAINT INDX_RUBRO_PK
       		 PRIMARY KEY (ID_RUBRO)
	, CONSTRAINT ID_CENTRO_FK
			 FOREIGN KEY (ID_CENTRO_COSTOS)
			 REFERENCES CENTROCOSTOS(ID_CENTRO)
    ) ;
	
-------------------------------------------------------------------------------	

REM ********************************************************************
REM Create the FACTURAS table to hold the LIST OF facturas

Prompt ******  Creating FACTURAS table ....
--DROP TABLE FACTURAS;

CREATE TABLE FACTURAS
	( ID_FACTURA INT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1)
	, FECHA DATE NOT NULL
	, ID_USUARIO INT NOT NULL
	);

CREATE UNIQUE INDEX INDX_FACTURA_PK
ON FACTURAS (ID_FACTURA);

ALTER TABLE FACTURAS
ADD ( CONSTRAINT INDX_FACTURA_PK
       		 PRIMARY KEY (ID_FACTURA)
	, CONSTRAINT ID_USUARIO_FK
			 FOREIGN KEY (ID_USUARIO)
			 REFERENCES USUARIOS(ID_USUARIO)
    ) ;
	
-------------------------------------------------------------------------------		

REM ********************************************************************
REM Create the COMPRAS table to hold LIST OF compras

Prompt ******  Creating COMPRAS table ....
--DROP TABLE COMPRAS;

CREATE TABLE COMPRAS
	( ID_COMPRA INT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1)
	, MONTO INT NOT NULL
	, PERMISO_COMPRA INT NOT NULL
	, CANTIDAD INT NOT NULL
	, ID_CENTRO_COSTOS INT NOT NULL
	, ID_USUARIO INT NOT NULL
	, ID_RUBRO INT NOT NULL
	, ID_FACTURA INT NOT NULL
	);

CREATE UNIQUE INDEX INDX_COMPRAS_PK
ON COMPRAS (ID_COMPRA);

ALTER TABLE COMPRAS
ADD ( CONSTRAINT INDX_COMPRAS_PK
       		 PRIMARY KEY (ID_COMPRA)
	, CONSTRAINT ID_CENTRO_COMPRAS_FK
			 FOREIGN KEY (ID_CENTRO_COSTOS)
			 REFERENCES CENTROCOSTOS(ID_CENTRO)
	, CONSTRAINT ID_USUARIO_COMPRAS_FK
			 FOREIGN KEY (ID_USUARIO)
			 REFERENCES USUARIOS(ID_USUARIO)
	, CONSTRAINT ID_RUBRO_COMPRAS_FK
			 FOREIGN KEY (ID_RUBRO)
			 REFERENCES RUBROS(ID_RUBRO)
	, CONSTRAINT ID_FACTURA_COMPRAS_FK
			 FOREIGN KEY (ID_FACTURA)
			 REFERENCES FACTURAS(ID_FACTURA)
    ) ;


-------------------------------------------------------------------------------	

REM ********************************************************************
REM Create the RUBROS_X_DEPARTAMENTO that sum all the visits per news

Prompt ******  Creating RUBROS_X_DEPARTAMENTO view ...

CREATE OR REPLACE VIEW RUBROS_X_DEPARTAMENTO
AS SELECT
		R.ID_RUBRO
	  , D.ID_DEPARTAMENTO
	  , R.ID_CENTRO_COSTOS
	  , D.ID_CENTRO_COSTOS
	  , C.MES_GASTO
	FROM RUBROS R, DEPARTAMENTOS D, CENTROCOSTOS C 
	WHERE R.ID_CENTRO_COSTOS = C.ID_CENTRO_COSTOS
		AND C.ID_CENTRO_COSTOS = D.ID_CENTRO_COSTOS

WITH READ ONLY;

COMMIT;